services:
  # Backend Service
  - type: web
    name: livesentiment-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: livesentiment-db
          property: connectionString
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: LiveSentiment
      - key: Jwt__Audience
        value: LiveSentiment
    healthCheckPath: /health

  # Frontend Service
  - type: web
    name: livesentiment-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: livesentiment-backend
          property: host

databases:
  - name: livesentiment-db
    plan: free
    databaseName: livesentiment
    user: livesentiment_user
