// <auto-generated />
using System;
using System.Text.Json.Nodes;
using LiveSentiment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LiveSentiment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250810094305_EditPresentationTable")]
    partial class EditPresentationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LiveSentiment.Models.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<JsonObject>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PresentationId");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("LiveSentiment.Models.Presentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PresenterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("PresenterId");

                    b.ToTable("Presentations");
                });

            modelBuilder.Entity("LiveSentiment.Models.Presenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LoginMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Presenters");
                });

            modelBuilder.Entity("LiveSentiment.Models.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("LiveSentiment.Models.SentimentAggregate", b =>
                {
                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AggregatedSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonObject>("EmotionCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonArray>("Keywords")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonObject>("SentimentCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("PollId");

                    b.ToTable("SentimentAggregates");
                });

            modelBuilder.Entity("LiveSentiment.Models.Poll", b =>
                {
                    b.HasOne("LiveSentiment.Models.Presentation", "Presentation")
                        .WithMany("Polls")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("LiveSentiment.Models.Presentation", b =>
                {
                    b.HasOne("LiveSentiment.Models.Presenter", "Presenter")
                        .WithMany("Presentations")
                        .HasForeignKey("PresenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presenter");
                });

            modelBuilder.Entity("LiveSentiment.Models.Response", b =>
                {
                    b.HasOne("LiveSentiment.Models.Poll", "Poll")
                        .WithMany("Responses")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("LiveSentiment.Models.SentimentAggregate", b =>
                {
                    b.HasOne("LiveSentiment.Models.Poll", "Poll")
                        .WithOne("SentimentAggregate")
                        .HasForeignKey("LiveSentiment.Models.SentimentAggregate", "PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("LiveSentiment.Models.Poll", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("SentimentAggregate")
                        .IsRequired();
                });

            modelBuilder.Entity("LiveSentiment.Models.Presentation", b =>
                {
                    b.Navigation("Polls");
                });

            modelBuilder.Entity("LiveSentiment.Models.Presenter", b =>
                {
                    b.Navigation("Presentations");
                });
#pragma warning restore 612, 618
        }
    }
}
